#!/usr/bin/env bash
set -e

#
# Constants
#
ENV_NAMES=(
  dev
  staging
  prod
)

DOMAIN_NAME="static.ENV.hl2.com"

HL2_HOSTED_ZONE_ID_dev="ZONZUS7Y70VH5"
HL2_HOSTED_ZONE_ID_staging="ZU9C2G1AWV2J3"
HL2_HOSTED_ZONE_ID_prod="Z8FQN0JAF0S3M"

ROUTE53_RECORDSET_CONFIG_FILE=./tools/conf/route53-recordset.json

#
# Functions
#
usage () {
    echo "usage: [-h] [--environment (dev|staging|prod)] [--force]"
    echo "    -h|--help         Help"
    echo "    -e|--environment  Deployment environment and aws profile name to use (default dev)"
    echo ""
    exit 1
}

errexit () {
  echo -e "\033[0;31m$1\033[0m"
  exit 1
}

warn(){
  echo -e "\033[0;33m$1\033[0m"
}

getEnvironmentDomainName() {
  local domainName=$DOMAIN_NAME
  if [[ $1 == 'prod' ]]; then
    echo ${domainName//.ENV/}
  else
    echo ${domainName//ENV/$1}
  fi
}

isValidEnvironment () {
  local isValid="false"
  for i in ${ENV_NAMES[@]}
  do
    if [[ $i = $1 ]] ; then
        isValid="true"
    fi
  done

  echo $isValid
}

#
# Main
#
while [ $# -gt 0 ]
do
  key="$1"
  case $key in
    -h|--help)
      usage
    ;;
    -e|--environment)
      environment=$2
      shift
    ;;
    *)
    usage
    ;;
  esac
  if [[ $# -gt 0 ]]; then
    shift
  fi
done

environment=${environment-dev}
hl2HostedZoneIdName=HL2_HOSTED_ZONE_ID_$environment
websiteName=$(getEnvironmentDomainName $environment)
echo "websiteName: $websiteName"
s3Endpoint="$websiteName.s3.amazonaws.com"

CLOUDFRONT_DISTRIBUTION_CONFIG_FILE=./tools/conf/cloudfront-distribution-$environment.json
distributionConfig=$(<$CLOUDFRONT_DISTRIBUTION_CONFIG_FILE)
distributionConfig=${distributionConfig//<DomainName>/$s3Endpoint}
distributionConfig=${distributionConfig//<WebsiteName>/$websiteName}

# Validate parameters
if [[ $(isValidEnvironment $environment) = "false" ]]; then
  usage
fi

echo "[INFO] S3: Check for existing bucket"
if ! aws s3api head-bucket --bucket "$websiteName" --profile $environment 2>/dev/null; then
  echo "[INFO] S3: Create website bucket"
  aws s3 mb s3://$websiteName --profile $environment || errexit "Could not create S3 bucket"
fi

echo "[INFO] S3: Enable website hosting"
aws s3 website s3://$websiteName \
  --profile $environment \
  --index-document index.html \
  --error-document error.html || errexit "Could not enable S3 website hosting"

echo "[INFO] S3: Synchronize bucket"
aws s3 sync dist/ s3://$websiteName \
  --profile $environment \
  --exclude '.*' \
  --exclude '**/.*' \
  --delete \
  --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers || errexit "Could not synchronize S3 bucket"

echo "[INFO] CloudFront: Check for existing distribution"
cloudfrontDistributionId=$(aws cloudfront list-distributions \
  --profile $environment \
  --query 'DistributionList.Items[?Aliases.Items[0]==`'$websiteName'`].Id | [0]' \
  --output text) || errexit "Could not check for existing distribution"

if [[ $cloudfrontDistributionId = "None" ]]; then
  echo "[INFO] CloudFront: Create distribution"
  cloudfrontDistributionDomainName=$(aws cloudfront create-distribution \
    --profile $environment \
    --distribution-config "$distributionConfig" \
    --query Distribution.DomainName
    --output text) || errexit "Could not create CloudFront distribution"

    warn "[WARN] Cloudfront: Please restart this script when this new distribution is deployed."
    warn "[WARN] Cloudfront: (see https://console.aws.amazon.com/cloudfront/home)"
    exit 1
else
  echo "[INFO] CloudFront: Update distribution"
  cloudfrontDistributionETag=$(aws cloudfront get-distribution \
    --profile $environment \
    --id $cloudfrontDistributionId \
    --query ETag \
    --output text) || errexit "Could not get distribution ETag"

  cloudfrontDistributionDomainName=$(aws cloudfront update-distribution \
    --profile $environment \
    --id $cloudfrontDistributionId \
    --if-match $cloudfrontDistributionETag \
    --distribution-config "$distributionConfig" \
    --query Distribution.DomainName \
    --output text) || errexit "Could not update distribution"
fi

echo "[INFO] Route53: Build record set configuration"
recordsetConfig=$(<$ROUTE53_RECORDSET_CONFIG_FILE)
recordsetConfig=${recordsetConfig//<WebsiteName>/$websiteName}
recordsetConfig=${recordsetConfig//<DNSName>/$cloudfrontDistributionDomainName}

echo "[INFO] Route53: Change record set"
aws route53 change-resource-record-sets \
  --profile $environment \
  --hosted-zone-id ${!hl2HostedZoneIdName} \
  --change-batch "$recordsetConfig" 1> /dev/null || errexit "Could not create the record set"
